# Base configs
baseurl: "https://odnavin.github.io/photography/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "by Odette"
# subtitle: "See the world through my eyes"
author: "Odette"
header:
 title: "Photography"
 subtitle: "Odette"
footer:
 name: "My name is Odette."
 bio: "Pairing intimate poetry with local photography, this digital anthology invites viewers to keep San Francisco, through every fractured and ambitious iteration, close to their hearts."
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "AJ"

 social_urls:
#  twitter: "https://www.twitter.com/rampatra_"
  instagram: "https://www.instagram.com/nb.nwhere?igsh=NTc4MTIwNjQ2YQ%3D%3D&utm_source=qr"
# dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
# github: "https://www.github.com/rampatra"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
